apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: prod
spec:
  encryptedData:
    password: AgABcDTUpiCzYvyJXqnw2VzB6xv63qr0WnHHghZuJjmq7qve9wrvpr6LY6+EUcx3b8TwjqyIvmuh4LEvAV3AsKvPgIfOOC+s7PdggdwZEsFQC+vc1i+cgE8B3tDkJvDQZSXxGbGPlAfEgJl4x49VTEn6LtKCl5IGcNKO863NF1OXE08DBaaM1uF0VH+bbAALLq2KtDdSfVpz/lYbSRcwX0wSV6uaTg9zyiqZR0092F21C9I04opgjnnHr9CoCoxTHA3cC8qCyJQJ87hylQvT8Li94lnOvz6sfzscFYc+jD2nHSN67397Ol89W3iz4YBgqyvNSSR/zP1E2W/Da1848HjWCY+Bo81yn1MOBO09iFDb0h3ZvId5s+4ImL0fx+lZTzBZv3pfzgGB4GGS1qvVpISnvMjlZ8oY5Wg2B65Cc7ZqkWFeWEcWIjJF12JfdUqDie33wWstlV4uGiuB0NPflMD/IIYDMRjj4K05b4A1ZDlIX08LS9c3LMjIRRESA/raRgoM2PErNAQW0yHL4vJuALKSCwxDP4ZjNBfi3WZcbgwbV0yTTyQYqBM3WuXIYrKp0nOO+IeV7z3BHaM4Qs14TK8uG4UEYgtxDFLCAbUsapQrwmgQ0lfnfUNcdJjndBVVjaw5NksiZYQy29ud7ljdEdLbihRDwfIHwOhiRdB9/nOhdtXI+RtlxpoyRRF/Cpknc3a7gaA15A==
    user: AgAwe0OfFgqT3Aq6Lx9mGSllGZ7RYhwWWGdb8gRY1xMTlbAIfxzm8cOQCD/ftJgFiaQsojbuW6T3FfyXJ3Q3lZh7RLGHixK05x9hc3L553/U6TcGXfsNGedNqY/Dkgurj0hb9lUoI5TpiBNW7sGU1K+HdfDoLl7+OWe+xxxBobhXDSxxib71LKKPs7/QaVgcDyU6OlWSBvLXa46GJD9VKfaukAjo+1i6dP1rvCDu7jBP9K2zaFIhYXQMCciU1SVl16YzJq5gg9C+NnVDfmAvphaqQJJhyRfX7b4DF/68tx2ci45lbi4gbA+bjwSGPT/9ghvhSEqaUIxuyxc4CUEaIABwZUi0mEQUBqLMSQlVdnP09NwqhRbJ9RjYbfycAqecFrdVhEKKMFHTfR2tJnJyuVBHKibIgO2VLaiIknSg3/BDSMNYW+9F2N2r77fXochNN2WaebhuCOTXoRM9ZmqAPJ+70+P13h2Wqku5G+DxNQVQXCVV3rCM5IXrCNTT4+6mJm7dyCVd09GjYLr2TDD844z1LbcjHsilBcNnPkl40BzTvn4tddHpLEO+cKZsnJ6av/EnQYTSTnEoecS5nOyL6FT69rprMN8RJcs3Di9K6fYpgmRGbYcaaVwno9DElFWzu4MfuMIN5kRlYrRAcsWu3N0+8vhDvrvjRA62j3e0Vd/r+CAvzl0fbLoj72RrTtgEGy9L7fg3NQ==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: prod
status: {}

